### ISSUE TITLE
Binary package specification in recipes is potentially insufficient

### ISSUE THREAD

**Issue by sapperlott** [pybombs/pybombs#139]
The mechanisms to specify binary packages in the recipes seem to be pretty limited. Basically we get to specify a list of versioned RPMs and/or DEBs per recipe and that's it. In the recipes I've looked at, there's almost always only a single package name listed. The problem here is that multiple distributions use DEB and RPM as their package format and each distro might name their packages differently. For RPM for example there's Fedora vs. openSUSE.

For my Fedora 21 install I already had to fix a handful of recipes to avoid unnecessary compilation of recipes from source (libusb -> libusbx was particularly nasty to figure out). Just changing these recipes in git isn't a real solution because then it might work for me but break for somebody else.

I realize that we could probably just include an ORed list of all the possible package names for all the different distros but that would get pretty unwieldy pretty fast. It might also cause other problems (for example matching the wrong package from another distro). So for this to really work well for as much users as possible, it seems that the way of specifying binary packages in recipes has to become distribution aware.

**Comment by osh** [comment]
I agree its not a perfect system, but it is meant to be relatively simple and easy to tailor for your local lab environment.   In the case of differing package names, we can add for example,
satisfy_deb: (libusb || libusbx)    
to allow either naming convention to satisfy it
not perfect - but it should resolve the case you describe
